### ISSUE TITLE
Assumes WebGL2 support on a system that only supports WebGL

### ISSUE THREAD

**Issue by GoranM** [dbandstra/oxid#25]
JavaScript console error:

```
Uncaught Error: The browser supports WebGL2, but initialization failed.
    at webgl.js:19
```

The system I'm using is quite old, and given the output of:

```
$ glxinfo | grep "OpenGL ES profile version"
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.107 340.107
```

I'm fairly certain that it doesn't support WebGL2, as that would require ES 3.0, at a minimum.

`typeof WebGL2RenderingContext !== 'undefined'` does not appear to be a valid method for WebGL2 detection.

The only way I know of, that seems to work, is to try getting a webgl2 context: If the returned object is null, assume it's not supported, and fall back to webgl.

**Comment by dbandstra** [comment]
Thanks for the report! I realized I wasn't using any WebGL2 functions so I just got rid of that code. Let me know if it works for you now.

**Comment by GoranM** [comment]
Works great now.

Thanks for the quick response.
