### ISSUE TITLE
Broken with latest Zig

### ISSUE THREAD

**Issue by dbandstra** [dbandstra/oxid#28]
With latest Zig, the game is somehow corrupted - sprites are mixed up, and the game eventually crashes if you shoot something.

I'm using commit ec2f9ef4e (Aug 23) for now, which works.

Track down which particular Zig commit broke this.

**Comment by andrewrk** [comment]
:scream:

**Comment by andrewrk** [comment]
If it helps, here is a directory listing of ziglang.org/builds/: https://clbin.com/f5KiE

**Comment by dbandstra** [comment]
Thanks. It's not urgent haha. I'll check it out later because I have a bunch of messy uncommitted work from the past week that I'm getting really sick of and I want to deal with that first.

Do you get notified on any activity in my project?

**Comment by andrewrk** [comment]
Yes, I have made a habit out of "watching" all projects written in Zig. It won't be sustainable forever, but for now I can try to help people when they run into trouble.

**Comment by dbandstra** [comment]
Broken by this commit (September 5) https://github.com/ziglang/zig/commit/2045b4d93240cd95eee7143f2cfc360eb63c5802 "prefer result type casting to peer type resolution"

Not really sure what next step to take, given that it's not a straightforward crash, but I'll try to poke around.

**Comment by andrewrk** [comment]
Thanks for tracking that down. I'll get this fixed for you

**Comment by dbandstra** [comment]
Thanks. I'm having some trouble because even adding a std.debug.warn call will change the behaviour of the program.

**Comment by andrewrk** [comment]
I was never able to identify the cause but I just tested against latest zig master (35c1d8cefc3a77b867ecc2da999162781099b4c6) everything appears to be fine.

**Comment by dbandstra** [comment]
You're right, it seems to work again. I don't have the energy to track down the commit that "fixed" this (especially with the LLVM upgrade in there), so let's just say we saw nothing...
